# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apellido', models.CharField(max_length=200)),
                ('Nombre', models.CharField(max_length=200)),
                ('Cumpleaños', models.DateField(verbose_name='Fecha de cumpleaños')),
                ('email', models.CharField(max_length=200)),
                ('Telefono', models.CharField(max_length=200)),
                ('Color_o_Tratamiento', models.CharField(max_length=200)),
                ('fecha', models.DateField(verbose_name='Fecha de Registro')),
            ],
        ),
    ]
