# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 04:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peluqueria', '0002_auto_20160709_0049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Telefono',
            new_name='Teléfono',
        ),
    ]
