# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peluqueria', '0004_auto_20160709_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Cumpleaños',
            field=models.DateField(blank=True, verbose_name='Fecha de cumpleaños'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Teléfono',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
