# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peluqueria', '0006_auto_20160709_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Registro'),
        ),
    ]
