# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 06:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peluqueria', '0007_auto_20160709_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de Registro'),
        ),
    ]
