# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peluqueria', '0008_auto_20160709_0326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Color_o_Tratamiento',
            new_name='Tratamiento',
        ),
    ]
