# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 03:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peluqueria', '0009_auto_20160711_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_operacion', models.DateField(default=datetime.date.today, verbose_name='Fecha de Operación')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lote', models.IntegerField()),
                ('fecha_pago', models.DateField(verbose_name='Fecha de pago')),
            ],
        ),
        migrations.CreateModel(
            name='TipoTarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tarjeta', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='tipo_tarjeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peluqueria.TipoTarjeta'),
        ),
    ]
