# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peluqueria', '0010_auto_20160818_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipotarjeta',
            name='tipo_tarjeta',
            field=models.CharField(max_length=50),
        ),
    ]
