# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 02:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peluqueria', '0014_auto_20160818_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_operacion', models.DateField(default=datetime.date.today, verbose_name='Fecha de Operación')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('concepto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoOperacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='caja',
            name='tipo_operacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peluqueria.TipoOperacion'),
        ),
    ]
